# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_statistics(object):
    def setupUi(self, statistics):
        statistics.setObjectName("statistics")
        statistics.resize(893, 600)
        statistics.setMinimumSize(QtCore.QSize(800, 600))
        self.verticalLayoutWidget = QtWidgets.QWidget(statistics)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 11, 871, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_history_clients = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_history_clients.setAlignment(QtCore.Qt.AlignCenter)
        self.label_history_clients.setObjectName("label_history_clients")
        self.verticalLayout.addWidget(self.label_history_clients)
        self.table_history_clients = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table_history_clients.setMinimumSize(QtCore.QSize(550, 500))
        self.table_history_clients.setObjectName("table_history_clients")
        self.table_history_clients.setColumnCount(4)
        self.table_history_clients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_history_clients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history_clients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history_clients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_history_clients.setHorizontalHeaderItem(3, item)
        self.table_history_clients.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.table_history_clients)

        self.retranslateUi(statistics)
        QtCore.QMetaObject.connectSlotsByName(statistics)

    def retranslateUi(self, statistics):
        _translate = QtCore.QCoreApplication.translate
        statistics.setWindowTitle(_translate("statistics", "Statistics"))
        self.label_history_clients.setText(_translate("statistics", "History"))
        item = self.table_history_clients.horizontalHeaderItem(0)
        item.setText(_translate("statistics", "Username"))
        item = self.table_history_clients.horizontalHeaderItem(1)
        item.setText(_translate("statistics", "IP"))
        item = self.table_history_clients.horizontalHeaderItem(2)
        item.setText(_translate("statistics", "Port"))
        item = self.table_history_clients.horizontalHeaderItem(3)
        item.setText(_translate("statistics", "Login time"))
