# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_active_clients = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_active_clients.setAlignment(QtCore.Qt.AlignCenter)
        self.label_active_clients.setObjectName("label_active_clients")
        self.verticalLayout.addWidget(self.label_active_clients)
        self.table_active_clients = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.table_active_clients.setObjectName("table_active_clients")
        self.table_active_clients.setColumnCount(4)
        self.table_active_clients.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_active_clients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_active_clients.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_active_clients.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_active_clients.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.table_active_clients)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        self.menuClients_history = QtWidgets.QMenu(self.menubar)
        self.menuClients_history.setObjectName("menuClients_history")
        self.menuServer_settings = QtWidgets.QMenu(self.menubar)
        self.menuServer_settings.setObjectName("menuServer_settings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuClients_history.menuAction())
        self.menubar.addAction(self.menuServer_settings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server"))
        self.label_active_clients.setText(_translate("MainWindow", "Active clients"))
        item = self.table_active_clients.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.table_active_clients.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.table_active_clients.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        item = self.table_active_clients.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Login time"))
        self.menuClients_history.setTitle(_translate("MainWindow", "Clients history"))
        self.menuServer_settings.setTitle(_translate("MainWindow", "Server settings"))
