# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(300, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(settings.sizePolicy().hasHeightForWidth())
        settings.setSizePolicy(sizePolicy)
        settings.setMinimumSize(QtCore.QSize(300, 220))
        self.buttonBox = QtWidgets.QDialogButtonBox(settings)
        self.buttonBox.setGeometry(QtCore.QRect(11, 180, 193, 28))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 11, 285, 162))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_view = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_view.setObjectName("btn_view")
        self.gridLayout_2.addWidget(self.btn_view, 1, 1, 1, 1)
        self.edit_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_port.setObjectName("edit_port")
        self.gridLayout_2.addWidget(self.edit_port, 3, 1, 1, 1)
        self.edit_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_path.setObjectName("edit_path")
        self.gridLayout_2.addWidget(self.edit_path, 1, 0, 1, 1)
        self.label_db_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_db_name.setObjectName("label_db_name")
        self.gridLayout_2.addWidget(self.label_db_name, 2, 0, 1, 1)
        self.label_port = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_port.setObjectName("label_port")
        self.gridLayout_2.addWidget(self.label_port, 3, 0, 1, 1)
        self.edit_db_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_db_name.setObjectName("edit_db_name")
        self.gridLayout_2.addWidget(self.edit_db_name, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_path = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_path.setObjectName("label_path")
        self.verticalLayout_2.addWidget(self.label_path)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(settings)
        self.buttonBox.accepted.connect(settings.accept) # type: ignore
        self.buttonBox.rejected.connect(settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Settings"))
        self.btn_view.setText(_translate("settings", "View"))
        self.label_db_name.setText(_translate("settings", "DB name:"))
        self.label_port.setText(_translate("settings", "Port:"))
        self.label_path.setText(_translate("settings", "Path to DB file:"))
